=== lantanagroup/TestDataGenerator/TestDataGenerator/ActionConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 sp1 (x64) (http://www.altova.com) by Tim Stevens (Lantana Group) -->
<!--W3C Schema generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ActionConfiguration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="namespaces">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="namespace" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="prefix" use="required"/>
									<xs:attribute name="uri" use="required"/>
									<xs:attribute name="location"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="good" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="instances">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="instance" type="instanceType" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="bad" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="instances">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="instance" type="instanceType" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="instanceType">
		<xs:sequence>
			<xs:element name="filter" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Specifies limits for when the instance is applied to the master file.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0">
							<xs:element name="randomRowCount">
								<xs:annotation>
									<xs:documentation>Applies the instance to a random row, but not to every row.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="maxOccur" type="xs:int" default="1"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="specificRowCount">
								<xs:annotation>
									<xs:documentation>Indicates that this instance should only be applied when the current row count matches the value specified. </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="value" type="xs:string">
										<xs:annotation>
											<xs:documentation>The rows that this filter should apply to within the section. Can take the following forms: "1,2-3,4,5-10,14-11"</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="section" type="xs:string">
										<xs:annotation>
											<xs:documentation>The section that the filter should apply to within the source data. Ex: "Header"</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="inherit" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Reference another instance that should be applied inherently through this instance. Any actions within the inherited instance will also be applied to this instance unless the filter of the inherited instance does not allow it to be applied. The createNew flag for inherited instances does not apply; new instances are never created for inherited instances.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="instanceName" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="action-remove">
					<xs:annotation>
						<xs:documentation>Removes an element or attribute from the instance.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="location" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="action-add">
					<xs:annotation>
						<xs:documentation>Adds an element or attribute to the instance.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice>
							<xs:element name="element">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="external" type="xs:anyType" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="name"/>
									<xs:attribute name="before"/>
									<xs:attribute name="after"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="attribute">
								<xs:complexType>
									<xs:attribute name="name" use="required"/>
									<xs:attribute name="value"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="location" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="action-set">
					<xs:annotation>
						<xs:documentation>Sets the value of an attribute or element to the value specified, or to nothing if no value is specified. If the node returned in the location is an element, the text() of the element is set to the value. If the node returned by the location is an attribute,t he value of the attribute is changed to the value specified </xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="location" use="required"/>
						<xs:attribute name="value"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="action-comment">
					<xs:complexType>
						<xs:attribute name="location" use="required"/>
						<xs:attribute name="value" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" use="required">
			<xs:annotation>
				<xs:documentation>The name of the instance, which will be used when saving the broken/bad file to the bad-file directory.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="rootContext">
			<xs:annotation>
				<xs:documentation>XPATH that represents the root context of the actions. For example, you may know that all actions will be performed within the documentationOf element, therefor the rootContext can be set to the XPATH of the documentationOf element and the action locations can point to relative locations to the documentationOf element.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="createNew" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>Determines whether or not to create a new copy of the master file or not. Default is "true"</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="isAbstract" type="xs:boolean" default="false">
			<xs:annotation>
				<xs:documentation>Abstract instances are not applied unless they are used via inheritence.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="actionSetType">
		<xs:sequence>
			<xs:element name="instance" type="instanceType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== lantanagroup/TestDataGenerator/TestDataGenerator.Tests/data/TestActionConfiguration.xml
<ActionConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ActionConfiguration.xsd">
  <good>
    <instances>
      <instance name="test3">
        <action-remove location="/cda:ClinicalDocument/cda:documentationOf"/>
        <action-remove location="/cda:ClinicalDocument/cda:author/cda:time/@value"/>
        <action-remove location="/cda:ClinicalDocument/cda:title"/>
      </instance>
      <instance name="test4" rootContext="/cda:ClinicalDocument/cda:component/cda:structuredBody/cda:component">
        <filter>
          <specificRowCount value="0" section="Results"/>
        </filter>
        <action-remove location="cda:entry/cda:observation/cda:effectiveTime"/>
        <action-set location="cda:entry/cda:observation/@typeCode" value="INVALID_TYPE_CODE"/>
      </instance>
    </instances>
  </good>
	<bad>
    <instances>
		  <instance name="test1">
			  <filter>
				  <randomRowCount/>
			  </filter>
			  <action-remove location="/cda:ClinicalDocument/cda:documentationOf"/>
			  <action-remove location="/cda:ClinicalDocument/cda:author/cda:time/@value"/>
			  <action-remove location="/cda:ClinicalDocument/cda:title"/>
		  </instance>
		  <instance name="test2" rootContext="/cda:ClinicalDocument/cda:component/cda:structuredBody/cda:component">
			  <filter>
				  <specificRowCount value="23" section="Results"/>
			  </filter>
			  <action-remove location="cda:entry/cda:observation/cda:effectiveTime"/>
			  <action-set location="cda:entry/cda:observation/@typeCode" value="INVALID_TYPE_CODE"/>
		  </instance>
    </instances>
	</bad>
</ActionConfiguration>
